### ISSUE TITLE
Error: No 'Unhandled' function defined for event: Unhandled

### ISSUE THREAD

**Issue by shavo007** [alexa/skill-sample-nodejs-calendar-reader#4]
Hi,

Get this error when i try to open skill:

```
{
  "session": {
    "sessionId": "SessionId",
    "application": {
      "applicationId": "amzn1.ask.skill."
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.accoun"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.a648b85c-0243-4214-8108-a132ab7442f4",
    "locale": "en-US",
    "timestamp": "2016-11-16T07:43:36Z",
    "intent": {
      "name": "searchIntent",
      "slots": {
        "date": {
          "name": "date"
        }
      }
    }
  },
  "version": "1.0"
}

```

Unexpected exception 'Error: No 'Unhandled' function defined for event: Unhandled':
Error: No 'Unhandled' function defined for event: Unhandled
at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:194:15)
at AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:160:23)
at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:116:25)
at AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:91:31)
at exports.handler (/var/task/index.js:270:11)

Any clue?

I have deployed the src exactly the way its defined.

Thanks,
Shane.

**Comment by shavo007** [comment]
Resolved.

I was testing on the simulator and just entered open.
