### ISSUE TITLE
Unexpected exception 'Error: No 'Unhandled' function defined for event: Unhandle

### ISSUE THREAD

**Issue by ArmenLevoni** [alexa/skill-sample-nodejs-calendar-reader#6]
after installing the sample and running the example, I am getting following error:

node index.js
Warning: Application ID is not set
Unexpected exception 'Error: No 'Unhandled' function defined for event: Unhandle
d':
Error: No 'Unhandled' function defined for event: Unhandled
    at AlexaRequestEmitter.EmitEvent (C:\Users\armkha01\AndroidStudioProjects\sk
ill-sample-nodejs-calendar-reader\src\node_modules\alexa-sdk\lib\alexa.js:194:15
),

this is due to "attributes": {}, attribute does not contains state by default, and example does not initilize the state.

**Comment by rickwargo** [comment]
This occurs because there is no default state. You must first open the skill without specifying any intent - just the LaunchRequest. If you wish to handle this, create an `Unhandled` handler in `newSessionHandlers` like this:

```
    'Unhandled': function () {
        this.emit(':ask', HelpMessage, HelpMessage);
    }
```

**Comment by smach** [comment]
I had the same problem. When I changed the code to be like this

    // Adding session handlers
    var newSessionHandlers = {
        'LaunchRequest': function () {
            this.handler.state = states.SEARCHMODE;
            this.emit(':ask', skillName + " " + welcomeMessage, welcomeMessage);
        },
    	'Unhandled': function () {
            this.emit(':ask', HelpMessage, HelpMessage);
        },
    };

The error was solved, but the app only gave the help message no matter what I asked it while testing.

**Comment by naweed-jaulim** [comment]
@smach did you manage to resolve it? I am getting the same error too.

**Comment by naweed-jaulim** [comment]
I just got it to work. Added the following:
'Unhandled': function() {
        this.emit(':ask', 'Insert your own error message here');
    },

**Comment by smach** [comment]
@Naweed80 Thanks for sharing. Where exactly did you add that? I tried that and then all my app does is return the error message, it never gets to actually searching.

**Comment by naweed-jaulim** [comment]
just after the launch request;
 'LaunchRequest': function () {
        this.emit('GetFact');
    },
'Unhandled': function() {
        this.emit(':ask', 'Insert your own error message here');
    },

**Comment by smach** [comment]
@Naweed80 Thanks again. That's exactly what I did and I'm still having the same issue, it just plays the error message and never searches. I'll check app ID, app name, and other variables meanwhile.

**Comment by smach** [comment]
@Naweed80 Thanks again. I've got

    // Adding session handlers
    var newSessionHandlers = {
        'LaunchRequest': function () {
            this.handler.state = states.SEARCHMODE;
            this.emit(':ask', skillName + " " + welcomeMessage, welcomeMessage);
        },
    	'Unhandled': function() {
    this.emit(':ask', 'Sorry I didnt understand that. Say help for assistance.');
    },
    };

In my index.js and still have the same problem of it only reading the error message. Will try to check other code. If you've got your code up on GitHub I'll try to use that.

**Comment by naweed-jaulim** [comment]
you also need to fix the app ID in the export handler - there is a pull request for it but don't think it's been merged.

here is my complete block.

exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.appId = APP_ID;
    // To enable string internationalization (i18n) features, set a resources object.
    alexa.resources = languageStrings;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

**Comment by smach** [comment]
@Naweed80 Thanks for your suggestions. Now I'm getting an invalid app ID if I change alexa.AppId to alexa.ap.Id. After spending several hours of my holiday on this, I think I'm admitting temporary defeat. I hope whomever posted this sample code will help make sure it works for everyone who follows the exact instructions in the tutorial!

**Comment by smach** [comment]
@Naweed80 Back to having it just read the help msg no matter what I do. Thanks for trying to help. I hope someone posts full code here that can be used as-is per the tutorial!

**Comment by tjanders** [comment]
I think I figured out what's going on here. [This link](https://developer.amazon.com/blogs/post/Tx213D2XQIYH864/announcing-the-alexa-skills-kit-for-node-js) about the alexa-sdk was a big help in figuring it out. There's essentially 3 states in this code. An initial state which is blank/empty string, _SEARCHMODE, and _DESKMODE, which are defined as constants at the top of index.js.

When a collection of handlers is created using Alexa.CreateStateHandler(), it actually appends the state to the end of your functions. So the searchIntent function actually becomes searchIntent_SEARCHMODE since it's added in startSearchHandlers where states.SEARCHMODE is passed in. The searchIntent function is the one you care about and would like it to execute by default.

When testing the skill, or trying to have it answer a question like, "Alexa, ask 'skill name' what's happening tonight", there is no state because it's the first time it's being called upon, so it's looking through the collection of newSessionHandlers to find a function named searchIntent, and guess what? It's not there. The only ones there are LaunchRequest and Unhandled as mentioned above. However, if you first say/test, "Alexa, launch 'skill name'", then this executes LaunchRequest and sets the state = SEARCHMODE, and all subsequent requests will now look for a function named searchIntent_SEARCHMODE, which does exist. Emitting "ask" at the end of LaunchRequest leaves the session open to listen for additional responses. If you tell the actual device to launch the skill, you'll notice the light ring stays blue waiting for additional commands. 

So...you could argue this is working as designed because launching it first creates a session you can interact with, but I agree with you that it should execute the search by default. Who wants to wait for a welcome message and instructions before asking it what's going on tonight? Not me. So to change the behavior, there's a few different options. You could copy the searchIntent function up to the newSessionHandlers, but that's not very DRY, so I don't like that. I think what I've settled on is adding this to the newSessionHandlers section just below LaunchRequest...

```
    'NewSession': function () {
        this.handler.state = states.SEARCHMODE;
        this.emit('searchIntent' + states.SEARCHMODE);
    }
```

NewSession will be called whenever the skill is first summoned. This sets the state to what we want it to be, and then passes off the execution to the handler we already created in startSearchHandlers, albeit with Amazon's naming convention built in.

I'm sure there are better ways to factor this code, and it does make an assumption that Amazon's CreateStateHandler naming convention never changes, but I hope this at least helps explain what's going on and gets you up and running. I'll leave it to the Amazon guys to comment if this is working as intended, or if the searchIntent should be the default intent when first executed.

**Comment by smach** [comment]
@tjanders Thanks so much for that very detailed explanation, which makes sense. I really appreciate you taking the time to explain! However, I was never able to get my Skill to read the calendar, even if I first opened the app and listened to the help message, and then asked it questions. 

I tried changing the newSessionhandlers section to this

    var newSessionHandlers = {
        'LaunchRequest': function () {
            this.handler.state = states.SEARCHMODE;
            this.emit(':ask', skillName + " " + welcomeMessage, welcomeMessage);
        },

    	  'NewSession': function () {
            this.handler.state = states.SEARCHMODE;
            this.emit('searchIntent' + states.SEARCHMODE);
        },
	
	
        'Unhandled': function () {
            this.emit(':ask', HelpMessage, HelpMessage);
        },
    };

But now am back to the `endpoints can't be reached` error when testing the app.  Lambda testing shows

`{
  "errorMessage": "Cannot read property 'slots' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "Object.Alexa.CreateStateHandler.searchIntent (/var/task/index.js:115:50)",
    "emitNone (events.js:67:13)",
    "AlexaRequestEmitter.emit (events.js:166:7)",
    "Object.newSessionHandlers.NewSession (/var/task/index.js:88:14)",
    "emitNone (events.js:67:13)",
    "AlexaRequestEmitter.emit (events.js:166:7)",
    "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:197:10)",
    "AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:160:23)",
    "AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:116:25)",
    "AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:91:31)"
  ]
}`

Do you have a full index.js file that's working to read the calendar? If so, and you can post it, that would be great.

Thanks again.

**Comment by rickwargo** [comment]
@smach I forked this repo to make a working calendar skill that is posted on github. I ran into similar problems as you. I resolved them similar to as described above, also added more functionality for dates. Feel free to download the code and use. 

https://github.com/rickwargo/skill-sample-nodejs-calendar-reader

**Comment by tjanders** [comment]
@smach I guess I needed a little more testing! The reason you're getting that error is because NewSession short-circuits every other function and gets called first. When you test with a LaunchRequest, you get the error you mentioned because the LaunchRequest is actually being handled by NewSession, passing off the request to searchIntent_SEARCHMODE, and it's dying further down the chain because there's no date value. That's actually an opportunity for better error handling, but we can worry about that later.

Since NewSession is always called, that's not what we want either. The better solution is to actually do the opposite - define the searchIntent function in newSessionHandlers, and reference it from startSearchHandlers. So I went back to my other suggestion and moved searchIntent into newSessionHandlers, and replaced it with this code inside startSearchHandlers...

```
    'searchIntent': function () {
        this.emit('searchIntent'); // Uses the handler in newSessionHandlers
    },
```

This is much cleaner because it doesn't rely on Amazon's naming conventions anymore. Also, since we want to set the state to SEARCHMODE when searchIntent is called, just like it does in LaunchRequest, we need to add this line inside the searchIntent function...

```
    'searchIntent': function () {
        // Declare variables 
        var eventList = new Array();
        var slotValue = this.event.request.intent.slots.date.value;
        var parent = this;

        this.handler.state = states.SEARCHMODE; // <---- ADD THIS LINE

        // Using the iCal library I pass the URL of where we want to get the data from.
        ical.fromURL(URL, {}, function (err, data) {
```

@rickwargo At first glance, it looks like you still need to launch the skill before requesting it to search for an event because you don't have a searchIntent in your newSessionHandler. I'm anxious to check out the added date functionality though!

**Comment by tjanders** [comment]
Fwiw, I've also decided to add the same searchIntent block below to descriptionHandlers. This allows searching for another event after an event was already found. Otherwise, if any event is found, it changes the state to _DESKMODE and you can never search for anything else until you relaunch the app.

```
    'searchIntent': function () {
        this.emit('searchIntent'); // Uses the handler in newSessionHandlers
    },
```

**Comment by smach** [comment]
@tjanders Thanks again for taking the time on this. I believe I tried your suggestions, but I ended up with this error message now:

    2017-01-07T04:15:37.061Z	f02ef62f-d48f-11e6-ac1f-6780b0c2d4f3	TypeError: Cannot read property 'split' of undefined
    at getDateFromSlot (/var/task/index.js:313:26)
    at /var/task/index.js:114:33
    at Request._callback (/var/task/node_modules/ical/node-ical.js:11:5)
    at Request.self.callback (/var/task/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/task/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:963:12)

**Comment by smach** [comment]
@rickwargo Thanks very much for posting your code. I tried it as is (except for changing the application ID).  Discovered I needed to install moment package, which I did. Unfortunately it doesn't seem to be working for me, I get the dreaded endpoint can't be called, the logs show

    2017-01-07T04:41:15.390Z	85efb921-d493-11e6-a826-b39a9c8bcea8	Unexpected exception   'TypeError: Cannot read property 'value' of undefined':
    TypeError: Cannot read property 'value' of undefined
    at Object.Alexa.CreateStateHandler.searchIntent (/var/task/index.js:133:63)
    at emitNone (events.js:67:13)
    at AlexaRequestEmitter.emit (events.js:166:7)
    at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:197:10)
    at AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:160:23)
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:116:25)
    at AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:91:31)
    at exports.handler (/var/task/index.js:324:11)

**Comment by rickwargo** [comment]
@smach hard to say what is wrong. My guess is that your interaction model is not set up like mine. I created a custom slot to handle group. So, in addition to intents.json for your Intent Schema, and SampleUtterances.txt for your Same Utterances (both in assets/speech), you will need to create a custom slot "GROUP". To make it work with mine, you'll need the values: 
SQL
center city
philadelphia
b. i.
business intelligence
jersey
south jersey

Feel free to contact me directly for more help.

**Comment by smach** [comment]
@rickwargo Thanks so much. It appears that I need to start simpler and work up to this calendar-reading skill. I thought after the Hello World skill worked, it would be easy to follow another tutorial step-by-step to get this cool skill working, but that appears not to be the case.

**Comment by rickwargo** [comment]
@smach No problem. Let me know if I can help later down the road. Good luck!

**Comment by soundarsurya** [comment]
hey anyone could tell me once again clearly.
i cannot understand from the above conversation...???

**Comment by soundarsurya** [comment]
because i am getting only this error......
if i can fix this error i will complete my project.
please anyone help me to fix this...
